version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: |
            sudo apt-get update && sudo apt-get install -y build-essential libbluetooth-dev
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            git clone --depth 1 git@github.com:6RiverSystems/ci_scripts.git
            ci_scripts/ci_tool.sh --setup_npm
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Calculate Version
          command: ci_scripts/ci_tool.sh --run_release
      - persist_to_workspace:
          root: ./
          paths:
            - .

  publish:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run release
          command: |
            ci_scripts/ci_tool.sh --setup_npm
      - run:
          name: npm publish
          command: npm publish
  test:
    docker:
      - image: ros:kinetic-ros-core-xenial
        environment:
          NODE_ENV: test
          CMAKE_PREFIX_PATH: /opt/ros/kinetic
          ROS_PACKAGE_PATH: /opt/ros/kinetic/share
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: setup node
          command: |
            sudo apt update &&\
            sudo apt install -q -y curl &&\
            curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o install_nvm.sh &&\
            bash install_nvm.sh &&\
            echo "sourcing .profile" &&\
            source ~/.profile &&\
            echo "sourcing .bashrc" &&\
            source ~/.bashrc &&\
            echo "nvm setup done"
      - run:
          name: install node
          command: |
            echo "set env var" &&\
            export NVM_DIR="$HOME/.nvm" &&\
            echo "run nvm script" &&\
            sh ~/.nvm/nvm.sh &&\
            echo "try install node" &&\
            nvm install 8.12.0
      - run:
          name: npm test
          command: |
            echo "run test" &&\
            npm test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: 6rs-circle
      - test:
          context: 6rs-circle
          requires:
            - build
      - publish:
          context: 6rs-circle
          requires:
            - build
            - test
